### ISSUE TITLE
Uncaught TypeError: currentView.getDirectoryPath is not a function

### ISSUE THREAD

**Issue by CharlyJazz** [rehrumesh/atom-sass#1]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.8.0
**System**: Microsoft Windows 7 Ultimate 
**Thrown From**: [atom-sass](https://github.com/rehrumesh/atom-sass) package, v0.2.0
### Stack Trace

Uncaught TypeError: currentView.getDirectoryPath is not a function

```
At C:\Users\Servio\.atom\packages\atom-sass\lib\compiler.js:30

TypeError: currentView.getDirectoryPath is not a function
    at C:\Users\Servio\.atom\packages\atom-sass\lib\compiler.js:30:47
    at Function.module.exports.Emitter.simpleDispatch (C:\Users\Servio\AppData\Local\atom\app-1.8.0\resources\app.asar\node_modules\event-kit\lib\emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (C:\Users\Servio\AppData\Local\atom\app-1.8.0\resources\app.asar\node_modules\event-kit\lib\emitter.js:125:28)
    at C:\Users\Servio\AppData\Local\atom\app-1.8.0\resources\app.asar\src\pane-container.js:346:27
    at Function.module.exports.Emitter.simpleDispatch (C:\Users\Servio\AppData\Local\atom\app-1.8.0\resources\app.asar\node_modules\event-kit\lib\emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (C:\Users\Servio\AppData\Local\atom\app-1.8.0\resources\app.asar\node_modules\event-kit\lib\emitter.js:125:28)
    at Pane.module.exports.Pane.setActiveItem (C:\Users\Servio\AppData\Local\atom\app-1.8.0\resources\app.asar\src\pane.js:282:22)
    at Pane.module.exports.Pane.activateItem (C:\Users\Servio\AppData\Local\atom\app-1.8.0\resources\app.asar\src\pane.js:431:21)
    at atom-tabs.TabBarView.onMouseDown (C:\Users\Servio\AppData\Local\atom\app-1.8.0\resources\app.asar\node_modules\tabs\lib\tab-bar-view.js:658:19)
```
### Commands

```
     -2:53.2.0 pane:move-active-item-to-top-of-stack (atom-text-editor.editor.autocomplete-active.is-focused)
     -2:50.9.0 editor:newline (atom-text-editor.editor.autocomplete-active.is-focused)
     -2:49.8.0 autocomplete-plus:confirm (atom-text-editor.editor.autocomplete-active.is-focused)
     -2:49.8.0 snippets:expand (atom-text-editor.editor.autocomplete-active.is-focused)
  5x -2:43.7.0 core:backspace (atom-text-editor.editor.is-focused)
     -2:39.5.0 core:save (atom-text-editor.editor.is-focused)
     -2:24.7.0 emmet:expand-abbreviation-with-tab (atom-text-editor.editor.is-focused.autocomplete-active)
     -2:22.6.0 core:copy (atom-text-editor.editor.is-focused)
     -2:21.8.0 core:select-right (atom-text-editor.editor.is-focused)
     -2:21.5.0 core:copy (atom-text-editor.editor.is-focused)
     -2:21 core:backspace (atom-text-editor.editor.is-focused)
     -2:19.9.0 core:paste (atom-text-editor.editor.is-focused)
     -2:19.5.0 core:save (atom-text-editor.editor.is-focused)
     -2:07.8.0 atom-sass:compile (atom-text-editor.editor.is-focused)
     -2:06.2.0 encoding-selector:show (atom-text-editor.editor.is-focused)
 11x -1:35.7.0 core:page-up (select#color-picker.triggerKey.form-control)
```
### Config

``` json
{
  "core": {
    "packagesWithKeymapsDisabled": [],
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
atom-sass, v0.2.0
color-picker, v2.2.1
emmet, v2.4.3

# Dev
No dev packages
```

**Comment by rehrumesh** [comment]
@CharlyJazz Thanks for reporting the issue with detailed description. I will look into this soon.

**Comment by skybluesofa** [comment]
+1

**Comment by rehrumesh** [comment]
@CharlyJazz @skybluesofa I have sent an update with fixes to current issues including this one. Please check the latest version. https://github.com/rehrumesh/atom-sass/releases/tag/v0.2.1

For now I am closing this issue. If you find anything else, please do open a new issue. If time permits, send a Fix as well. :) :+1:  Thanks
